export const styles = {
  tiny: ["rounded", "w-[18px]", "h-[18px]", "text-xs"].join(" "),
  sm: ["rounded-md", "w-6", "h-6", "text-sm"].join(" "),
  md: ["rounded-md", "w-8", "h-8", "text-base"].join(" "),
  lg: ["rounded-lg", "w-12", "h-12", "text-lg"].join(" "),
  normal: {
    wrapper: [
      "flex",
      "items-center",
      "justify-center",
      "cursor-pointer",
      "ring-2",
      "ring-transparent",
      "active:ring-2",
      "active:ring-blue-alpha-200",
      "disabled:bg-grey-alpha-100",
      "disabled:text-disabled",
      "disabled:ring-2",
      "disabled:ring-transparent",
      "disabled:cursor-default",
    ].join(" "),
    primary: [
      "bg-accent-primary",
      "text-accent-contrast",
      "hover:bg-accent-light",
      "active:bg-accent-medium",
    ].join(" "),
    secondary: [
      "bg-neutral-alpha-200",
      "text-primary",
      "hover:bg-neutral-alpha-200",
      "active:bg-neutral-alpha-200",
    ].join(" "),
    outlined: [
      "bg-surface",
      "text-primary",
      "border",
      "border-light",
      "hover:border-dark",
      "active:border-dark",
      "disabled:border-disabled",
    ].join(" "),
    "primary-transparent": [
      "text-accent-primary",
      "bg-transparent",
      "hover:bg-neutral-alpha-200",
      "hover:text-accent-medium",
      "active:bg-blue-alpha-100",
      "active:text-accent-primary",
      "disabled:bg-transparent",
    ].join(" "),
    "secondary-transparent": [
      "text-secondary",
      "bg-transparent",
      "hover:bg-neutral-alpha-200",
      "hover:text-primary",
      "active:bg-blue-alpha-100",
      "active:text-accent-primary",
      "disabled:bg-transparent",
    ].join(" "),
  },
};
